(function initFields(global) {
  const OfferCome = global.OfferCome = global.OfferCome || {};

  const field = (path, label, aliases, options = {}) => ({ path, label, aliases, ...options });

  OfferCome.FIELD_DEFINITIONS = [
    field("basics.fullName", "姓名", ["姓名", "中文姓名", "真实姓名", "name", "fullname", "candidate name", "applicant name"], { autocomplete: ["name"] }),
    field("basics.englishName", "英文名", ["英文名", "英文姓名", "english name", "preferred name"]),
    field("basics.gender", "性别", ["性别", "gender", "sex"], { kind: "choice" }),
    field("basics.birthDate", "出生日期", ["出生日期", "出生年月", "生日", "birthdate", "date of birth", "birthday"], { kind: "date" }),
    field("basics.nationality", "国籍", ["国籍", "国家", "nationality", "citizenship", "country of citizenship"], { kind: "choice" }),
    field("basics.ethnicity", "民族", ["民族", "ethnicity", "ethnic group"], { kind: "choice" }),
    field("basics.politicalStatus", "政治面貌", ["政治面貌", "political status"], { kind: "choice" }),
    field("basics.maritalStatus", "婚姻状况", ["婚姻状况", "婚姻状态", "marital status"], { kind: "choice" }),
    field("basics.healthStatus", "健康状况", ["健康状况", "身体状况", "健康状态", "health status"], { kind: "choice" }),
    field("basics.phone", "手机号", ["手机号", "手机号码", "联系电话", "电话", "移动电话", "phone", "mobile", "phone number", "telephone"], { autocomplete: ["tel", "tel-national"] }),
    field("basics.alternatePhone", "备用电话", ["备用电话", "其他电话", "alternate phone", "secondary phone"]),
    field("basics.email", "邮箱", ["邮箱", "电子邮箱", "邮件", "email", "email address", "e-mail"], { autocomplete: ["email"] }),
    field("basics.alternateEmail", "备用邮箱", ["备用邮箱", "其他邮箱", "alternate email", "secondary email"]),
    field("basics.idType", "证件类型", ["证件类型", "证件类别", "id type", "identity type"], { kind: "choice", sensitive: true }),
    field("basics.idNumber", "证件号码", ["身份证号", "身份证号码", "证件号码", "证件号", "id number", "identity number", "national id"], { sensitive: true }),
    field("basics.nativePlace", "籍贯", ["籍贯", "native place", "hometown"], { kind: "choice" }),
    field("basics.sourcePlace", "生源地", ["生源地", "生源所在地", "生源省市", "place of student origin", "student origin"], { kind: "choice" }),
    field("basics.birthPlace", "出生地", ["出生地", "出生地点", "place of birth", "birthplace"]),
    field("basics.hukou", "户口所在地", ["户口", "户籍", "户口所在地", "户籍所在地", "household registration", "hukou"]),
    field("basics.preCollegeHukou", "入学前户口所在地", ["入学前户口所在地", "入学前户籍", "入学前户口"], { kind: "choice" }),
    field("basics.currentProvince", "现居省份", ["现居省份", "所在省", "居住省份", "province", "state"], { kind: "choice" }),
    field("basics.currentCity", "现居城市", ["现居城市", "所在城市", "居住城市", "当前城市", "city", "current city"], { kind: "choice" }),
    field("basics.currentDistrict", "现居区县", ["现居区县", "所在区县", "居住区县", "district", "county"], { kind: "choice" }),
    field("basics.address", "详细地址", ["详细地址", "现居地址", "联系地址", "通讯地址", "居住地址", "address", "street address", "current address"], { autocomplete: ["street-address"] }),
    field("basics.postalCode", "邮编", ["邮编", "邮政编码", "postal code", "zip", "zipcode"], { autocomplete: ["postal-code"] }),
    field("basics.wechat", "微信", ["微信", "微信号", "wechat", "weixin"]),
    field("basics.qq", "QQ", ["qq", "qq号", "腾讯qq"]),
    field("basics.website", "个人网站", ["个人网站", "个人主页", "website", "personal website", "homepage"]),
    field("basics.github", "GitHub", ["github", "github主页", "github url"]),
    field("basics.linkedin", "LinkedIn", ["linkedin", "领英", "linkedin url", "linkedin profile"]),
    field("basics.portfolio", "作品集", ["作品集", "作品链接", "portfolio", "portfolio url"]),
    field("basics.targetCity", "期望城市", ["期望城市", "意向城市", "工作地点", "期望工作地点", "preferred location", "desired city"]),
    field("basics.targetPosition", "期望职位", ["期望职位", "意向职位", "求职意向", "目标岗位", "desired position", "target role"]),
    field("basics.expectedSalary", "期望薪资", ["期望薪资", "期望工资", "薪资要求", "expected salary", "salary expectation"]),
    field("basics.availableDate", "可入职日期", ["可入职日期", "到岗日期", "最快到岗", "available date", "start date", "availability"], { kind: "date" }),
    field("basics.summary", "个人简介", ["个人简介", "自我介绍", "自我评价", "个人总结", "summary", "profile", "about yourself"]),
    field("basics.strengths", "个人优势", ["个人优势", "核心优势", "特长", "strengths", "key strengths"]),
    field("basics.hobbies", "兴趣爱好", ["兴趣爱好", "爱好", "hobbies", "interests"]),
    field("basics.domesticGraduate", "是否境内毕业生", ["是否为境内毕业生", "境内毕业生"], { kind: "choice" }),
    field("basics.hongKongMacaoUniversityStudent", "是否港澳籍大学生", ["是否为港澳籍大学生", "港澳籍大学生"], { kind: "choice" }),
    field("basics.taiwanRegisteredUniversityStudent", "是否台湾籍大学生", ["是否为台湾籍大学生", "台湾籍大学生"], { kind: "choice" }),
    field("basics.scienceEngineeringMajor", "是否理工类专业", ["是否理工类专业", "理工类专业"], { kind: "choice" }),
    field("basics.engineeringMasterDoctorProgram", "工程硕博专项", ["是否为工程硕博联合培养专项人员", "工程硕博专项", "联合培养专项"], { kind: "choice" }),

    field("education.school", "学校", ["学校", "学校名称", "毕业院校", "院校", "university", "school", "institution"], { section: "education" }),
    field("education.college", "学院", ["学院", "院系", "college", "faculty", "department"], { section: "education" }),
    field("education.schoolLocation", "学校所在地", ["学校所在地", "院校所在地", "学校城市", "school location"], { section: "education" }),
    field("education.major", "专业", ["专业", "专业名称", "major", "field of study", "discipline"], { section: "education" }),
    field("education.majorCategory", "专业类别", ["专业类别", "学科类别", "专业大类", "major category"], { section: "education", kind: "choice" }),
    field("education.degreeLevel", "学历", ["学历", "最高学历", "教育程度", "education level", "degree level"], { section: "education", kind: "choice" }),
    field("education.degree", "学位", ["学位", "degree", "academic degree"], { section: "education", kind: "choice" }),
    field("education.startDate", "入学日期", ["入学日期", "入学时间", "教育开始时间", "start date", "from"], { section: "education", kind: "date", dateRole: "start" }),
    field("education.endDate", "毕业日期", ["毕业日期", "毕业时间", "教育结束时间", "end date", "to"], { section: "education", kind: "date", dateRole: "end" }),
    field("education.gpa", "GPA", ["gpa", "绩点", "平均绩点", "grade point average"], { section: "education" }),
    field("education.gpaScale", "GPA 满分", ["gpa满分", "绩点满分", "gpa scale"], { section: "education" }),
    field("education.rank", "排名", ["排名", "专业排名", "年级排名", "rank", "class rank"], { section: "education" }),
    field("education.courses", "主修课程", ["主修课程", "核心课程", "课程", "courses", "relevant coursework"], { section: "education" }),
    field("education.research", "研究方向", ["研究方向", "研究领域", "research direction", "research area"], { section: "education" }),
    field("education.advisor", "导师", ["导师", "指导老师", "指导教师", "supervisor", "advisor"], { section: "education" }),
    field("education.enrollmentType", "培养方式", ["培养方式", "受教育类型", "招生方式", "统招类型", "学习形式", "学习方式", "study mode", "enrollment type"], { section: "education", kind: "choice" }),
    field("education.fullTime", "是否全日制", ["是否全日制", "全日制", "full time education", "full-time education"], { section: "education", kind: "choice" }),
    field("education.overseasStudy", "海外学习经历", ["是否有海外学习经历", "海外学习经历", "overseas study"], { section: "education", kind: "choice" }),
    field("education.description", "教育描述", ["教育描述", "在校经历", "教育经历描述", "description"], { section: "education" }),

    field("experience.company", "公司", ["公司", "公司名称", "工作单位", "实习单位", "company", "employer", "organization"], { section: "experience" }),
    field("experience.department", "部门", ["部门", "所在部门", "department", "team"], { section: "experience" }),
    field("experience.position", "职位", ["职位", "岗位", "职务", "职位名称", "job title", "position", "role"], { section: "experience" }),
    field("experience.type", "工作类型", ["工作类型", "经历类型", "任职类型", "实习类型", "employment type", "work type"], { section: "experience", kind: "choice" }),
    field("experience.city", "工作城市", ["工作城市", "工作地点", "地点", "location", "work location"], { section: "experience" }),
    field("experience.startDate", "工作开始日期", ["开始日期", "开始时间", "入职时间", "start date", "from"], { section: "experience", kind: "date", dateRole: "start" }),
    field("experience.endDate", "工作结束日期", ["结束日期", "结束时间", "离职时间", "end date", "to"], { section: "experience", kind: "date", dateRole: "end" }),
    field("experience.description", "工作描述", ["工作描述", "工作内容", "工作职责", "实习内容", "职责描述", "description", "responsibilities", "job duties"], { section: "experience" }),
    field("experience.achievements", "工作成果", ["工作成果", "主要成果", "业绩", "achievements", "accomplishments"], { section: "experience" }),
    field("experience.reasonForLeaving", "离职原因", ["离职原因", "reason for leaving"], { section: "experience" }),
    field("experience.monthlySalary", "月薪", ["月薪", "职位月薪", "薪酬", "monthly salary"], { section: "experience" }),
    field("experience.verifier.name", "证明人姓名", ["证明人姓名", "证明人", "reference name", "referee name"], { section: "experience", sensitive: true }),
    field("experience.verifier.relationship", "证明人关系", ["证明人关系", "与证明人关系", "reference relationship"], { section: "experience", sensitive: true }),
    field("experience.verifier.position", "证明人职务", ["证明人职务", "reference position", "referee title"], { section: "experience", sensitive: true }),
    field("experience.verifier.company", "证明人单位", ["证明人单位", "reference company", "referee organization"], { section: "experience", sensitive: true }),
    field("experience.verifier.phone", "证明人联系方式", ["证明人联系方式", "证明人电话", "reference phone"], { section: "experience", sensitive: true }),

    field("projects.name", "项目名称", ["项目名称", "项目", "project name", "project title"], { section: "projects" }),
    field("projects.role", "项目角色", ["项目角色", "担任角色", "项目职务", "role", "project role"], { section: "projects" }),
    field("projects.startDate", "项目开始日期", ["开始日期", "项目开始时间", "start date", "from"], { section: "projects", kind: "date", dateRole: "start" }),
    field("projects.endDate", "项目结束日期", ["结束日期", "项目结束时间", "end date", "to"], { section: "projects", kind: "date", dateRole: "end" }),
    field("projects.url", "项目链接", ["项目链接", "项目地址", "project url", "project link"], { section: "projects" }),
    field("projects.techStack", "技术栈", ["技术栈", "使用技术", "tools", "technologies", "tech stack"], { section: "projects" }),
    field("projects.description", "项目描述", ["项目描述", "项目介绍", "description", "project description"], { section: "projects" }),
    field("projects.responsibilities", "项目职责", ["项目职责", "职责", "responsibilities", "contribution"], { section: "projects" }),
    field("projects.achievements", "项目成果", ["项目成果", "成果", "achievements", "result"], { section: "projects" }),

    field("campus.hasCadreExperience", "是否有学生干部经历", ["是否有担任学生干部经历", "是否有学生干部经历", "学生干部经历"], { section: "campus", kind: "choice" }),
    field("campus.cadreLevel", "干部级别", ["干部级别", "学生干部级别", "担任学生干部的级别"], { section: "campus", kind: "choice" }),
    field("campus.cadrePosition", "干部职级", ["干部职级", "学生干部职级", "担任学生干部的职级", "校园职务", "担任职务", "社团职务"], { section: "campus", kind: "choice" }),
    field("campus.startDate", "校园经历开始日期", ["开始日期", "开始时间", "start date"], { section: "campus", kind: "date", dateRole: "start" }),
    field("campus.endDate", "校园经历结束日期", ["结束日期", "结束时间", "end date"], { section: "campus", kind: "date", dateRole: "end" }),
    field("campus.description", "学生干部工作描述", ["工作描述", "主要职责", "工作成果", "工作亮点", "经历描述", "工作内容", "社团经历", "校园经历", "description"], { section: "campus" }),

    field("skills.name", "技能名称", ["技能名称", "专业技能", "技能", "skill", "skill name"], { section: "skills" }),
    field("skills.level", "技能熟练度", ["熟练度", "掌握程度", "技能等级", "proficiency", "skill level"], { section: "skills", kind: "choice" }),
    field("skills.description", "技能描述", ["技能描述", "技能说明", "description"], { section: "skills" }),

    field("languages.name", "语言", ["语言", "语种", "外语", "language"], { section: "languages", kind: "choice" }),
    field("languages.level", "语言等级", ["语言等级", "熟练程度", "掌握程度", "proficiency", "language level"], { section: "languages", kind: "choice" }),
    field("languages.score", "语言成绩", ["语言成绩", "考试分数", "成绩", "score", "test score"], { section: "languages" }),
    field("languages.description", "语言说明", ["听说读写", "语言说明", "description"], { section: "languages" }),
    field("languages.listeningSpeaking", "听说能力", ["听说能力", "口语能力", "listening", "speaking"], { section: "languages", kind: "choice" }),
    field("languages.readingWriting", "读写能力", ["读写能力", "阅读能力", "写作能力", "reading", "writing"], { section: "languages", kind: "choice" }),

    field("certificates.name", "证书名称", ["证书名称", "资格证书", "认证名称", "certificate", "certification"], { section: "certificates" }),
    field("certificates.issuer", "颁发机构", ["颁发机构", "发证机构", "issuer", "issuing organization"], { section: "certificates" }),
    field("certificates.date", "获证日期", ["获证日期", "取得日期", "颁发日期", "issue date", "date awarded"], { section: "certificates", kind: "date" }),
    field("certificates.number", "证书编号", ["证书编号", "证书号码", "certificate number", "credential id"], { section: "certificates" }),
    field("certificates.score", "证书成绩", ["等级分数", "证书分数", "考试分数", "score"], { section: "certificates" }),

    field("awards.name", "奖项名称", ["奖项名称", "荣誉名称", "获奖名称", "award", "honor"], { section: "awards" }),
    field("awards.level", "奖项级别", ["奖项级别", "获奖级别", "级别", "award level"], { section: "awards", kind: "choice" }),
    field("awards.date", "获奖日期", ["获奖日期", "获奖时间", "award date", "date awarded"], { section: "awards", kind: "date" }),
    field("awards.description", "奖项说明", ["奖项说明", "获奖说明", "description"], { section: "awards" }),
    field("awards.type", "奖项类型", ["奖项类型", "奖励类型", "award type"], { section: "awards", kind: "choice" }),
    field("awards.issuer", "评选单位", ["评选单位", "颁奖单位", "授予单位", "issuer", "awarding organization"], { section: "awards" }),

    field("publications.type", "论文/专利类型", ["类型", "成果类型", "论文类型", "专利类型", "著作类型", "publication type"], { section: "publications", kind: "choice" }),
    field("publications.title", "论文/专利名称", ["论文/专利名称", "论文专利名称", "论文名称", "专利名称", "成果名称", "题目", "title", "publication title", "patent title"], { section: "publications" }),
    field("publications.channel", "发表/授权渠道", ["发表/授权渠道", "发表授权渠道", "发表渠道", "授权渠道", "发表期刊", "期刊名称", "会议名称", "publication venue", "journal", "conference"], { section: "publications" }),
    field("publications.authorOrder", "作者顺序", ["作者顺序", "作者排名", "署名顺序", "作者位次", "author order", "author position"], { section: "publications", kind: "choice" }),
    field("publications.impactFactor", "影响因子", ["影响因子", "影响因子if", "if", "impact factor"], { section: "publications" }),
    field("publications.patentNumber", "专利号", ["专利号", "专利编号", "申请号", "授权号", "patent number", "application number"], { section: "publications" }),
    field("publications.date", "发表/授权时间", ["发表/授权时间", "发表授权时间", "发表时间", "授权时间", "公开时间", "publication date", "patent date"], { section: "publications", kind: "date" }),
    field("publications.url", "论文/专利链接", ["论文/专利链接", "论文专利链接", "论文链接", "专利链接", "成果链接", "doi", "publication url", "patent url"], { section: "publications" }),
    field("publications.details", "论文/专利详情", ["详情", "论文详情", "专利详情", "成果详情", "论文描述", "专利描述", "摘要", "description", "details", "abstract"], { section: "publications" }),

    field("family.name", "家庭成员姓名", ["姓名", "成员姓名", "亲属姓名", "name"], { section: "family", sensitive: true }),
    field("family.relationship", "家庭关系", ["关系", "与本人关系", "亲属关系", "relationship"], { section: "family", sensitive: true, kind: "choice" }),
    field("family.company", "家庭成员单位", ["工作单位", "单位名称", "公司", "公司名称", "company", "employer"], { section: "family", sensitive: true }),
    field("family.position", "家庭成员职务", ["职务", "职位", "position", "job title"], { section: "family", sensitive: true }),
    field("family.phone", "家庭成员电话", ["联系电话", "手机号", "电话", "phone"], { section: "family", sensitive: true }),

    field("answers.careerPlan", "职业规划", ["职业规划", "未来规划", "career plan", "career goals"]),
    field("answers.whyCompany", "申请原因", ["为什么选择", "为什么申请", "申请原因", "加入我们", "why company", "why do you want", "motivation"]),
    field("answers.strengthsAndWeaknesses", "优缺点", ["优点和缺点", "优势与不足", "优缺点", "strengths and weaknesses"]),
    field("answers.acceptOvertime", "是否接受加班", ["接受加班", "是否加班", "overtime"], { kind: "choice" }),
    field("answers.acceptTravel", "是否接受出差", ["接受出差", "是否出差", "business travel", "travel"], { kind: "choice" }),
    field("answers.acceptRelocation", "是否接受调剂", ["接受调剂", "是否调剂", "relocation", "relocate"], { kind: "choice" }),
    field("answers.relativesInCompany", "亲属关系", ["亲属在本公司", "亲属关系", "relative", "family member employed"], { kind: "choice", allowedSections: ["family"] }),
    field("answers.source", "信息来源", ["信息来源", "招聘渠道", "获知渠道", "how did you hear", "source"], { kind: "choice" })
  ];

  OfferCome.SECTION_ALIASES = {
    education: ["教育经历", "教育背景", "学历信息", "education", "academic"],
    experience: ["实习/工作经历", "实习工作经历", "实习/工作单位", "实习工作单位", "工作所在单位", "任职单位", "工作经历", "实习经历", "职业经历", "工作经验", "experience", "employment", "work history", "internship"],
    projects: ["项目经历", "项目经验", "科研项目", "project"],
    campus: ["学生会/社团活动", "学生会社团活动", "学生会", "社团活动", "学生干部", "干部级别", "干部职级", "校园经历", "社团经历", "学生工作", "校内实践", "campus", "activity"],
    skills: ["专业技能", "技能", "技术能力", "skills", "technical skills"],
    languages: ["语言能力", "外语能力", "语言", "languages", "language skills"],
    certificates: ["证书", "资格证书", "认证", "certificates", "certifications"],
    awards: ["奖项", "荣誉", "获奖经历", "awards", "honors"],
    publications: ["论文/专利", "论文专利", "论文发表情况", "专利情况", "学术成果", "科研成果", "论文", "专利", "软著", "publications", "publication", "patents", "patent"],
    family: ["家庭成员", "家庭情况", "家属信息", "家属", "亲属信息", "亲属", "family", "family members", "relative"]
  };
})(globalThis);
